apiVersion: v1
kind: Service
metadata:
    name: web
    labels:
        env: dev
        run: web
spec:
    selector:
        run: nginx
    type: NodePort 
    ports:
        - port: 8080
          name: nginx-listner
          nodePort: 30000
          targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
    name: registry
    labels:
        env: dev
        run: registry
spec:
    selector:
        run: registry
    type: NodePort
    ports:
        - port: 5000
          name: registry-listner
          nodePort: 30001
          targetPort: 5000

